apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: express-app
    newName: ghcr.io/ivanderkendrick/express-devops-app
    newTag: sha-be21439
